apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: webhook-receiver-rolebinding
subjects:
  - kind: ServiceAccount
    name: webhook-receiver-sa
    namespace: default
roleRef:
  kind: ClusterRole
  name: webhook-receiver-role
  apiGroup: rbac.authorization.k8s.io